#!/usr/bin/env python3
"""Regenerate the sample input files under examples/.

The files are derived from the same analytic models as the built-in demo
data (see crates/smith-sphere-core/src/demo.rs) so imports can be checked
against known impedances. Run from the repository root:

    python3 scripts/generate_examples.py
"""

from __future__ import annotations

import cmath
import math
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "examples"
Z0 = 50.0


def sweep(start: float, stop: float, points: int) -> list[float]:
    return [start + (stop - start) * i / (points - 1) for i in range(points)]


def series_rlc(f: float, r: float = 25.0, l: float = 10e-9, c: float = 5e-12) -> complex:
    w = 2 * math.pi * f
    return complex(r, w * l - 1 / (w * c))


def negative_device(f: float) -> complex:
    w = 2 * math.pi * f
    g = complex(1 / -40.0, w * 2e-12)
    return 1 / g + complex(0, w * 2e-9)


def crossing(f: float) -> complex:
    t = (f - 1e9) / 1e9
    return complex(-30 + 60 * t, -40 + 80 * t * t)


def gamma(z: complex) -> complex:
    return (z - Z0) / (z + Z0)


def fmt(x: float) -> str:
    return f"{x:.9g}"


def write(name: str, text: str) -> None:
    (OUT / name).write_text(text, encoding="utf-8")
    print("wrote", OUT / name)


def touchstone_1port(frequencies_hz: list[float], model, form: str, unit: str, scale: float, comment: str) -> str:
    lines = [f"! {comment}", f"! Generated by scripts/generate_examples.py, demo data, not a measurement", f"# {unit} S {form} R 50"]
    for f in frequencies_hz:
        g = gamma(model(f))
        if form == "RI":
            a, b = g.real, g.imag
        elif form == "MA":
            a, b = abs(g), math.degrees(cmath.phase(g))
        else:
            a, b = 20 * math.log10(abs(g)), math.degrees(cmath.phase(g))
        lines.append(f"{fmt(f / scale)} {fmt(a)} {fmt(b)}")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.mkdir(exist_ok=True)
    rlc = sweep(100e6, 2e9, 77)
    write("series_rlc_ma.s1p", touchstone_1port(rlc, series_rlc, "MA", "MHz", 1e6, "Series RLC demo: R = 25 ohm, L = 10 nH, C = 5 pF"))
    write("series_rlc_ri.s1p", touchstone_1port(rlc, series_rlc, "RI", "GHz", 1e9, "Series RLC demo: R = 25 ohm, L = 10 nH, C = 5 pF"))
    write("series_rlc_db.s1p", touchstone_1port(rlc, series_rlc, "DB", "Hz", 1.0, "Series RLC demo: R = 25 ohm, L = 10 nH, C = 5 pF"))
    csv = ["frequency (MHz),R,X"] + [f"{fmt(f / 1e6)},{fmt(series_rlc(f).real)},{fmt(series_rlc(f).imag)}" for f in rlc]
    write("series_rlc.csv", "\n".join(csv) + "\n")

    neg = sweep(100e6, 3e9, 59)
    write("negative_resistance.s1p", touchstone_1port(neg, negative_device, "RI", "GHz", 1e9, "Ideal negative-resistance model: -40 ohm || 2 pF, then 2 nH in series"))

    cross = sweep(1e9, 2e9, 40)
    csv = ["freq (GHz)\tR\tX"] + [f"{fmt(f / 1e9)}\t{fmt(crossing(f).real)}\t{fmt(crossing(f).imag)}" for f in cross]
    write("crossing_r_zero.tsv", "\n".join(csv) + "\n")
    csv = ["freq,R,X"] + [f"{fmt(f / 1e9)},{fmt(crossing(f).real)},{fmt(crossing(f).imag)}" for f in cross]
    write("crossing_no_unit.csv", "\n".join(csv) + "\n")

    # Two-port demo: port 1 sees the series RLC, port 2 sees the crossing
    # model; transmission terms are placeholders and are never plotted.
    lines = [
        "! Two-port demo: S11 = series RLC, S22 = crossing model, S21/S12 placeholders",
        "! Generated by scripts/generate_examples.py, demo data, not a measurement",
        "# GHz S MA R 50",
    ]
    for f in sweep(1e9, 2e9, 21):
        g11 = gamma(series_rlc(f))
        g22 = gamma(crossing(f))
        first = f"{fmt(f / 1e9)} {fmt(abs(g11))} {fmt(math.degrees(cmath.phase(g11)))} 0.5 -20"
        second = f"      0.5 -20 {fmt(abs(g22))} {fmt(math.degrees(cmath.phase(g22)))}"
        lines.append(first)
        lines.append(second)
    lines.append("! Noise parameters: frequency restarts, this block must be skipped")
    lines.append("1 1.5 0.3 45 0.2")
    lines.append("2 1.8 0.2 60 0.3")
    write("two_port_demo.s2p", "\n".join(lines) + "\n")

    write(
        "magnitude_only.csv",
        "frequency (GHz),|S11|\n1,0.5\n1.5,0.4\n2,0.3\n",
    )
    write(
        "touchstone_v2_unsupported.s1p",
        "[Version] 2.0\n# GHz S MA R 50\n[Number of Ports] 1\n[Network Data]\n1 0.5 30\n[End]\n",
    )


if __name__ == "__main__":
    main()
