#!/usr/bin/env python3
"""Writes LICENSES/THIRD-PARTY.txt from the resolved Cargo dependency graph.

The file lists every crate compiled into the native or WebAssembly build with
its version, license, authors, and repository. Run it after changing
dependencies. `--check` exits non-zero when the committed file is stale.
"""

import argparse
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "LICENSES" / "THIRD-PARTY.txt"
TARGETS = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
WORKSPACE_PREFIX = "smith-sphere"

HEADER = """Third-party Rust crates compiled into SmithSphere.

Each entry gives the crate, its version, the SPDX license expression declared
by its authors, and where to find the source. Where a crate offers a choice of
licenses, SmithSphere uses it under the MIT License when available, otherwise
under the Apache License 2.0. The license texts are in this directory and at
the repository root. Bundled fonts are listed separately in NOTICE.

Generated by scripts/third_party_notices.py.
"""


def resolved_packages(target: str) -> dict:
    command = [
        "cargo",
        "metadata",
        "--format-version",
        "1",
        "--locked",
        "--filter-platform",
        target,
    ]
    metadata = json.loads(subprocess.check_output(command, cwd=ROOT))
    resolved = {node["id"] for node in metadata["resolve"]["nodes"]}
    return {
        package["id"]: package
        for package in metadata["packages"]
        if package["id"] in resolved and not package["name"].startswith(WORKSPACE_PREFIX)
    }


def render() -> str:
    packages = {}
    for target in TARGETS:
        packages.update(resolved_packages(target))
    lines = [HEADER]
    for package in sorted(packages.values(), key=lambda p: (p["name"], p["version"])):
        license_text = package.get("license") or f"see {package.get('license_file')}"
        lines.append(f"{package['name']} {package['version']}")
        lines.append(f"  license: {license_text}")
        if package.get("authors"):
            lines.append(f"  authors: {', '.join(package['authors'])}")
        if package.get("repository"):
            lines.append(f"  source: {package['repository']}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the file is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT.relative_to(ROOT)} is stale, run scripts/third_party_notices.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
