//! Bundled font installation. Source Han Sans CN (SIL OFL 1.1) provides the
//! Chinese interface text; the egui defaults remain as fallbacks.

use egui::{Context, FontData, FontDefinitions, FontFamily};
use std::sync::Arc;

/// Glyph subset generated by `scripts/subset_font.py`.
pub const UI_FONT: &[u8] =
    include_bytes!("../../../assets/fonts/SourceHanSansCN-Regular.subset.otf");
const UI_FONT_NAME: &str = "SourceHanSansCN";

/// Installs the bundled font as the primary proportional face and as a
/// fallback for the monospace family.
pub fn install(context: &Context) {
    let mut fonts = FontDefinitions::default();
    fonts.font_data.insert(
        UI_FONT_NAME.to_owned(),
        Arc::new(FontData::from_static(UI_FONT)),
    );
    fonts
        .families
        .entry(FontFamily::Proportional)
        .or_default()
        .insert(0, UI_FONT_NAME.to_owned());
    fonts
        .families
        .entry(FontFamily::Monospace)
        .or_default()
        .push(UI_FONT_NAME.to_owned());
    context.set_fonts(fonts);
}

#[cfg(test)]
mod tests {
    use super::*;
    use ab_glyph::Font as _;

    /// Every Rust source file of the workspace, because interface strings live
    /// in all three crates.
    fn workspace_sources() -> Vec<String> {
        let crates = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("crate lives under crates/");
        let mut pending = vec![crates.to_path_buf()];
        let mut sources = Vec::new();
        while let Some(directory) = pending.pop() {
            for entry in std::fs::read_dir(&directory).expect("directory is readable") {
                let path = entry.expect("entry is readable").path();
                if path.is_dir() {
                    pending.push(path);
                } else if path.extension().is_some_and(|extension| extension == "rs") {
                    sources.push(std::fs::read_to_string(&path).expect("source is UTF-8"));
                }
            }
        }
        assert!(sources.len() > 5, "expected the workspace sources");
        sources
    }

    #[test]
    fn bundled_font_covers_every_non_ascii_character_in_the_interface() {
        let font = ab_glyph::FontRef::try_from_slice(UI_FONT).expect("font parses");
        let mut missing = Vec::new();
        for source in workspace_sources() {
            for character in source
                .chars()
                .filter(|c| !c.is_ascii() && !c.is_whitespace())
            {
                if font.glyph_id(character).0 == 0 && !missing.contains(&character) {
                    missing.push(character);
                }
            }
        }
        assert!(
            missing.is_empty(),
            "run scripts/subset_font.py; missing glyphs: {missing:?}"
        );
    }
}
