//! Bundled font installation. Source Han Sans CN (SIL OFL 1.1) provides the
//! Chinese interface text; the egui defaults remain as fallbacks.

use egui::{Context, FontData, FontDefinitions, FontFamily};
use std::sync::Arc;

/// Glyph subset generated by `scripts/subset_font.py`.
pub const UI_FONT: &[u8] =
    include_bytes!("../../../assets/fonts/SourceHanSansCN-Regular.subset.otf");
const UI_FONT_NAME: &str = "SourceHanSansCN";

/// Installs the bundled font as the primary proportional face and as a
/// fallback for the monospace family.
pub fn install(context: &Context) {
    let mut fonts = FontDefinitions::default();
    fonts.font_data.insert(
        UI_FONT_NAME.to_owned(),
        Arc::new(FontData::from_static(UI_FONT)),
    );
    fonts
        .families
        .entry(FontFamily::Proportional)
        .or_default()
        .insert(0, UI_FONT_NAME.to_owned());
    fonts
        .families
        .entry(FontFamily::Monospace)
        .or_default()
        .push(UI_FONT_NAME.to_owned());
    context.set_fonts(fonts);
}

#[cfg(test)]
mod tests {
    use super::*;
    use ab_glyph::Font as _;

    const SOURCES: [&str; 5] = [
        include_str!("app.rs"),
        include_str!("dialogs.rs"),
        include_str!("../../smith-sphere-core/src/demo.rs"),
        include_str!("../../smith-sphere-core/src/format.rs"),
        include_str!("../../smith-sphere-render/src/chart.rs"),
    ];

    #[test]
    fn bundled_font_covers_every_non_ascii_character_in_the_interface() {
        let font = ab_glyph::FontRef::try_from_slice(UI_FONT).expect("font parses");
        let mut missing = Vec::new();
        for source in SOURCES {
            for character in source
                .chars()
                .filter(|c| !c.is_ascii() && !c.is_whitespace())
            {
                if font.glyph_id(character).0 == 0 && !missing.contains(&character) {
                    missing.push(character);
                }
            }
        }
        assert!(
            missing.is_empty(),
            "run scripts/subset_font.py; missing glyphs: {missing:?}"
        );
    }
}
